name: Smoker Status Prediction - ML Pipeline CI/CD

on:
  push:
    branches:
      - main

jobs:
  setup-and-install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  run-unit-tests:
    needs: setup-and-install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Unit Tests
      run: python -m unittest discover -s src/tests/unit

  run-integration-tests:
    needs: run-unit-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Integration Tests
      run: python -m unittest discover -s src/tests/integration

  run-system-tests:
    needs: run-integration-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run System Tests
      run: python -m unittest discover -s src/tests/system

  run-quality-assurance-tests:
    needs: run-system-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Quality Assurance/User Acceptance Tests
      run: python -m unittest discover -s src/tests/quality-assurance  

  train-model:
    needs: run-quality-assurance-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run train pipeline
      run: python src/pipeline/train_pipeline.py
